# Generated by Django 5.0.6 on 2024-05-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datashow',
            table='financial_reports',
        ),
    ]
