# Generated by Django 5.0.6 on 2024-05-20 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datashow',
            options={'managed': False},
        ),
    ]
